[[task]]
name = "heartbeat"
cron = "0 * * * * *"
timezone = "UTC"
type = "native"

[[task]]
name = "cache-cleanup"
cron = "0 */5 * * * *"
timezone = "Asia/Seoul"
type = "native"

[[task]]
name = "wasm-hello"
cron = "*/2 * * * * *"
timezone = "UTC"
type = "wasm"
payload = "hello.wasm"

[[task]]
name = "weather-station"
cron = "*/30 * * * * *"
timezone = "Asia/Seoul"
type = "wasm"
payload = "weather_station.wasm"

[[task]]
name = "ssh foo"
cron = "* * * * * *"
timezone = "Asia/Seoul"
type = "wasm"
payload = "ssh.wasm"
args = [
  "1.ctb.seungjin.net",
  "432",
  "seungjin",
  "file:~/.ssh/id_ed25519",
  "hostname",
  "key",
]
