[sqlite_database.mem]
type = "spin"

[key_value_store.mem]
type = "spin"

[sqlite_database.lachuoi]
type = "libsql"
url = "https://.turso.io"
token = "..."

[sqlite_database.geoname]
type = "libsql"
url = "https://.turso.io"
token = "..."




