spin_manifest_version = 2

[application]
name = "lachuoi"
version = "0.2.0"
authors = ["Seungjin Kim <seungjin@duck.com>"]
description = "https://github.com/seungjin/lachuoi"

[variables]
internal_key = { required = true }

newspenguin_rss_uri = { required = true }
newspenguin_mstd_api_uri = { required = true }
newspenguin_mstd_access_token = { required = true }

mstd_random_restaurant_mstd_access_token = { required = true }
mstd_random_restaurant_mstd_api_uri = { required = true }
mstd_random_restaurant_google_location_api_key = { required = true }

mstd_random_cafe_mstd_access_token = { required = true }
mstd_random_cafe_mstd_api_uri = { required = true }
mstd_random_cafe_google_location_api_key = { required = true }

google_ai_api_key = { required = true }

image_description_google_ai_api_uri = { required = true }
image_description_google_ai_prompt = { required = true }
wsj_mstd_api_uri = { required = true }
wsj_mstd_access_token = { required = true }

servant_mstd_api_uri = { required = true }
servant_mstd_access_token = { required = true }

logger_auth_table = { required = true }

################################################################################
# Trigger
################################################################################

[[trigger.http]]
route = "/"
component = "doormat"

[[trigger.http]]
route = "/static/..."
component = "assets"

[[trigger.http]]
route = "/place"
component = "place"

[[trigger.http]]
route = "/place/random/..."
component = "place-random"

[[trigger.http]]
route = "/place/timezone/..."
component = "place-timezone"

[[trigger.http]]
route = "/place/population/..."
component = "place-population"

[[trigger.http]]
route = "/ifconfig/..."
component = "ifconfig"

[[trigger.http]]
route = "/image/description/..."
component = "image-description"

[[trigger.http]]
route = "/logger/..."
component = "logger"

[[trigger.http]]
route = ".well-known/webfinger"
component = "webfinger"

# Grain compile takes too long
# [[trigger.http]]
# route = "/edge/grain/..."
# component = "hello-grain"
# executor = { type = "wagi" }

[[trigger.http]]
route = "/geoip/..."
component = "geoip"

[[trigger.http]]
route = "/ap/user"
component = "ap-user"

[[trigger.http]]
route = "/time/..."
component = "time"

[[trigger.http]]
route = "/ssl/check"
component = "ssl-check"

[[trigger.cron]]
component = "newspenguin-rss"
cron_expression = "1 1 1 1 * *"

[[trigger.cron]]
component = "mstd-random-restaurant"
cron_expression = "1 1 1 1 * *"

[[trigger.cron]]
component = "mstd-random-cafe"
cron_expression = "1 1 1 1 * *"

[[trigger.cron]]
component = "mstd-wsj-rss"
cron_expression = "1 1 1 1 * *"

[[trigger.cron]]
component = "mstd-servant"
cron_expression = "1 1 * * * *"

################################################################################
# Componenet
################################################################################

[component.assets]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "assets", destination = "/" }]

[component.doormat]
source = { url = "https://github.com/lachuoi/doormat/releases/download/v0.0.1/doormat.wasm", digest = "39ed75f7e324382b79f06e85e9b4ad009ac5a031d7aaeb9a1ce78cc4fde9ce32" }
# allowed_outbound_hosts = ["http://random-place.spin.internal"]

[component.mstd-random-restaurant]
source = "wasm/mstd_random_restaurant.wasm"
# allowed_outbound_hosts = ["http://place-random.spin.internal"]
allowed_outbound_hosts = [
  "http://localhost:3000",
  "https://maps.googleapis.com",
  "https://*.googleusercontent.com",
  "https://mstd.seungjin.net",
]
sqlite_databases = ["lachuoi"]

[component.mstd-random-cafe]
source = "wasm/mstd_random_cafe.wasm"
# allowed_outbound_hosts = ["http://place-random.spin.internal"]
allowed_outbound_hosts = [
  "http://localhost:3000",
  "https://maps.googleapis.com",
  "https://*.googleusercontent.com",
  "https://mstd.seungjin.net",
]
sqlite_databases = ["lachuoi"]

[component.place]
source = "wasm/place.wasm"

[component.place-random]
source = "wasm/place_random.wasm"
key_value_stores = ["mem"]
sqlite_databases = ["geoname"]
allowed_outbound_hosts = [
  "https://geoname-seungjin.turso.io",
  "https://raw.githubusercontent.com",
]

[component.place-timezone]
source = "wasm/place_timezone.wasm"

[component.place-population]
source = "wasm/place_population.wasm"

[component.ifconfig]
source = "wasm/ifconfig.wasm"
allowed_outbound_hosts = ["http://localhost:3000"]

[component.newspenguin-rss]
source = "wasm/newspenguin_rss.wasm"
sqlite_databases = ["lachuoi"]
allowed_outbound_hosts = [
  "https://www.newspenguin.com",
  "https://feedpub-seungjin.turso.io",
  "https://mstd.seungjin.net",
]

[component.image-description]
source = "wasm/image_description.wasm"
allowed_outbound_hosts = ["https://generativelanguage.googleapis.com"]

[component.mstd-wsj-rss]
source = "wasm/mstd_wsj_rss.wasm"
sqlite_databases = ["lachuoi"]
allowed_outbound_hosts = [
  "https://feeds.content.dowjones.io",
  "https://mstd.seungjin.net",
  "https://raw.githubusercontent.com",
]

[component.webfinger]
source = "wasm/webfinger.wasm"
sqlite_databases = ["lachuoi"]

# [component.hello-grain]
# source = "wasm/hello_grain.wasm"

[component.geoip]
source = "wasm/geoip.wasm"
files = [{ source = "resource/geoip", destination = "/" }]

[component.ap-user]
source = "wasm/ap_user.wasm"
sqlite_databases = ["lachuoi"]

[component.mstd-servant]
source = "wasm/mstd_servant.wasm"
sqlite_databases = ["lachuoi"]
allowed_outbound_hosts = [
  "https://feeds.content.dowjones.io",
  "https://www.economist.com",
  "https://mstd.seungjin.net",
  "https://raw.githubusercontent.com",
  "https://theconversation.com",
]

[component.time]
source = "wasm/time.wasm"

[component.logger]
source = "wasm/logger.wasm"
sqlite_databases = ["log"]

[component.ssl-check]
source = "wasm/ssl_check.wasm"

################################################################################
# Variables
################################################################################
[component.newspenguin-rss.variables]
rss_uri = "{{ newspenguin_rss_uri }}"
mstd_api_uri = "{{ newspenguin_mstd_api_uri }}"
mstd_access_token = "{{ newspenguin_mstd_access_token }}"

[component.mstd-random-restaurant.variables]
mstd_access_token = "{{ mstd_random_restaurant_mstd_access_token }}"
mstd_api_uri = "{{ mstd_random_restaurant_mstd_api_uri }}"
google_location_api_key = "{{ mstd_random_restaurant_google_location_api_key }}"

[component.mstd-random-cafe.variables]
mstd_access_token = "{{ mstd_random_cafe_mstd_access_token }}"
mstd_api_uri = "{{ mstd_random_cafe_mstd_api_uri }}"
google_location_api_key = "{{ mstd_random_cafe_google_location_api_key }}"

[component.image-description.variables]
google_ai_api_key = "{{ google_ai_api_key }}"

google_ai_api_uri = "{{ image_description_google_ai_api_uri }}"
google_ai_prompt = "{{ image_description_google_ai_prompt }}"

[component.mstd-wsj-rss.variables]
mstd_api_uri = "{{ wsj_mstd_api_uri }}"
mstd_access_token = "{{ wsj_mstd_access_token }}"

[component.mstd-servant.variables]
mstd_api_uri = "{{ servant_mstd_api_uri }}"
mstd_access_token = "{{ servant_mstd_access_token }}"

[component.logger.variables]
auth_table = "{{ logger_auth_table }}"


################################################################################
# Build
################################################################################


[component.mstd-random-restaurant.build]
command = "just build mstd-random-restaurant"

[component.mstd-random-cafe.build]
command = "just build mstd-random-cafe"

[component.place-random.build]
command = "just build place-random"

[component.place-population.build]
command = "just build place-population"

[component.ifconfig.build]
command = "just build ifconfig"

[component.newspenguin-rss.build]
command = "just build newspenguin-rss"

[component.image-description.build]
command = "just build image-description"

[component.webfinger.build]
command = "just build webfinger"

# Grain compile takes too long
# [component.hello-grain.build]
# command = "cd apps/hello-grain; grain compile ./src/main.gr -o ../../wasm/hello_grain.wasm; chmod +x ../../wasm/hello_grain.wasm"

[component.mstd-wsj-rss.build]
command = "just build mstd-wsj-rss"

[component.mstd-servant.build]
command = "just build mstd-servant"

[component.time.build]
command = "just build time"

[component.logger.build]
command = "just build logger"

[component.ssl-check.build]
command = "just build ssl-check"
