spin_manifest_version = 2

[application]
name = "lachuoi"
version = "0.2.0"
authors = ["Seungjin Kim <seungjin@duck.com>"]
description = "https://github.com/seungjin/lachuoi"

[variables]
internal_key = { required = true }

newspenguin_rss_uri = { required = true }
newspenguin_mstd_api_uri = { required = true }
newspenguin_mstd_access_token = { required = true }

mstd_random_restaurant_mstd_access_token = { required = true }
mstd_random_restaurant_mstd_api_uri = { required = true }
mstd_random_restaurant_google_location_api_key = { required = true }

mstd_random_cafe_mstd_access_token = { required = true }
mstd_random_cafe_mstd_api_uri = { required = true }
mstd_random_cafe_google_location_api_key = { required = true }

google_ai_api_key = { required = true }

image_description_google_ai_api_uri = { required = true }
image_description_google_ai_prompt = { required = true }

wsj_mstd_api_uri = { required = true }
wsj_mstd_access_token = { required = true }

servant_mstd_api_uri = { required = true }
servant_mstd_access_token = { required = true }


################################################################################
# Trigger
################################################################################

[[trigger.http]]
route = "/"
component = "root"

[[trigger.http]]
route = "/static/..."
component = "assets"

[[trigger.http]]
route = "/random-place/..."
# route = { private = true }
component = "random-place"

[[trigger.http]]
route = "/ifconfig/..."
component = "ifconfig"

[[trigger.http]]
route = "/image/description/..."
component = "image-description"

[[trigger.http]]
route = ".well-known/webfinger"
component = "webfinger"

[[trigger.http]]
route = "/geoip/..."
component = "geoip"

[[trigger.http]]
route = "/ap/user/..."
component = "ap-user"

[[trigger.cron]]
component = "newspenguin-rss"
cron_expression = "0 */15 * * * *"

[[trigger.cron]]
component = "mstd-random-restaurant"
cron_expression = "0 20 0,6,12,18 * * *"

[[trigger.cron]]
component = "mstd-random-cafe"
cron_expression = "0 40 3,9,15,21 * * *"

[[trigger.cron]]
component = "mstd-wsj-rss"
cron_expression = "10 */15 * * * *"

[[trigger.cron]]
component = "mstd-servant"
cron_expression = "40 */10 * * * *"


################################################################################
# Componenet
################################################################################

[component.assets]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "assets", destination = "/" }]

[component.root]
source = "wasm/root.wasm"
# allowed_outbound_hosts = ["http://random-place.spin.internal"]

[component.mstd-random-restaurant]
source = "wasm/mstd_random_restaurant.wasm"
# allowed_outbound_hosts = ["http://random-place.spin.internal"]
allowed_outbound_hosts = ["http://localhost:3000",
                          "https://maps.googleapis.com",
                          "https://*.googleusercontent.com",
                          "https://mstd.seungjin.net"]
sqlite_databases = ["lachuoi"]

[component.mstd-random-cafe]
source = "wasm/mstd_random_cafe.wasm"
# allowed_outbound_hosts = ["http://random-place.spin.internal"]
allowed_outbound_hosts = ["http://localhost:3000",
                          "https://maps.googleapis.com",
                          "https://*.googleusercontent.com",
                          "https://mstd.seungjin.net"]
sqlite_databases = ["lachuoi"]

[component.random-place]
source = "wasm/random_place.wasm"
key_value_stores = ["mem"]
sqlite_databases = ["geoname", "mem"]
allowed_outbound_hosts = ["https://geoname-seungjin.turso.io",
                          "https://raw.githubusercontent.com"]

[component.ifconfig]
source = "wasm/ifconfig.wasm"
allowed_outbound_hosts = ["http://localhost:3000"]

[component.newspenguin-rss]
source = "wasm/newspenguin_rss.wasm"
sqlite_databases = ["lachuoi"]
allowed_outbound_hosts = ["https://www.newspenguin.com",
                          "https://feedpub-seungjin.turso.io",
                          "https://mstd.seungjin.net"]

[component.image-description]
source = "wasm/image_description.wasm"
allowed_outbound_hosts = ["https://generativelanguage.googleapis.com"]

[component.mstd-wsj-rss]
source = "wasm/wsj_rss.wasm"
sqlite_databases = ["lachuoi"]
allowed_outbound_hosts = ["https://feeds.content.dowjones.io",
                          "https://mstd.seungjin.net",
                          "https://raw.githubusercontent.com"]

[component.webfinger]
source = "wasm/webfinger.wasm"

[component.geoip]
source = "wasm/geoip.wasm"
files = [{ source = "resource/geoip", destination = "/" }]

[component.ap-user]
source = "wasm/ap_user.wasm"
sqlite_databases = ["lachuoi"]

[component.mstd-servant]
source = "wasm/mstd_servant.wasm"
sqlite_databases = ["lachuoi"]
allowed_outbound_hosts = ["https://feeds.content.dowjones.io",
                          "https://mstd.seungjin.net",
                          "https://raw.githubusercontent.com"]

################################################################################
# Variables
################################################################################
[component.newspenguin-rss.variables]
rss_uri = "{{ newspenguin_rss_uri }}"
mstd_api_uri = "{{ newspenguin_mstd_api_uri     " 
mstd_access_token = "{{ newspenguin_mstd_access_token }}"

[component.mstd-random-restaurant.variables]
mstd_access_token = "{{ mstd_random_restaurant_mstd_access_token }}"
mstd_api_uri = "{{ mstd_random_restaurant_mstd_api_uri }}"
google_location_api_key = "{{ mstd_random_restaurant_google_location_api_key }}"

[component.mstd-random-cafe.variables]
mstd_access_token = "{{ mstd_random_cafe_mstd_access_token }}"
mstd_api_uri = "{{ mstd_random_cafe_mstd_api_uri }}"
google_location_api_key = "{{ mstd_random_cafe_google_location_api_key }}"

[component.i10ge-description.variables]
google_ai_api_key = "{{ google_ai_api_key }}"
google_ai_api_uri = "{{ image_description_google_ai_api_uri }}"
google_ai_prompt =  "{{ image_description_google_ai_prompt }}"

[component.mstd-wsj-rss.variables]
mstd_api_uri = "{{ wsj_mstd_api_uri }}" 
mstd_access_token = "{{ wsj_mstd_access_token }}"

[component.mstd-servant.variables]
mstd_api_uri = "{{ servant_mstd_api_uri }}" 
mstd_access_token = "{{ servant_mstd_access_token }}"

