spin_manifest_version = 2

[application]
name = "place"
version = "0.1.0"
authors = ["Seungjin Kim <seungjin@duck.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "place"

[component.place]
source = "target/wasm32-wasip1/release/place.wasm"
allowed_outbound_hosts = []

[component.place.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
