spin_manifest_version = 2

[application]
name = "image-description"
version = "0.1.0"
authors = ["Seungjin Kim <seungjin@duck.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "image-description"

[component.image-description]
source = "target/wasm32-wasip1/release/image_description.wasm"
allowed_outbound_hosts = []

[component.image-description.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
