spin_manifest_version = 2

[application]
name = "rantom-place"
version = "0.1.0"
authors = ["Seungjin Kim <seungjin@duck.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "random-place"

[component.random-place]
source = "target/wasm32-wasip1/release/random_place.wasm"
allowed_outbound_hosts = ["https://geoname-seungjin.turso.io"]

[component.random-place.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
