spin_manifest_version = 2

[application]
name = "ap-user"
version = "0.1.0"
authors = ["Seungjin Kim <seungjin@duck.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "ap-user"

[component.ap-user]
source = "target/wasm32-wasip1/release/ap_user.wasm"
allowed_outbound_hosts = []

[component.root.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
