# spin.toml
spin_manifest_version = 2

[application]
name = "hello-go"
version = "1.0.0"

[[trigger.http]]
route = "/hello"
component = "hello-go"

[component.hello-go]
source = "main.wasm"

[component.hello-go.build]
command = "tinygo build -target=wasip1 -gc=leaking -buildmode=c-shared -no-debug -o main.wasm ."

