spin_manifest_version = 2

[application]
authors = ["Seungjin Kim <seungjin@duck.com>"]
description = ""
name = "hello-world"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "hello-world"

[component.hello-world]
source = "app.wasm"
[component.hello-world.build]
command = "uv run componentize-py -w spin-http componentize app -o app.wasm"
watch = ["*.py", "requirements.txt"]
