spin_manifest_version = 2

[application]
name = "fq-test"
version = "0.1.0"
authors = ["Seungjin Kim <seungjin@duck.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "fq-test"

[component.fq-test]
source = "target/wasm32-wasip1/release/fq_test.wasm"
allowed_outbound_hosts = ["https://api.foursquare.com"]

[component.fq-test.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
